// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetContext(arg1) {
  return window['go']['bridge']['Bridge']['SetContext'](arg1);
}

export function StartClock(arg1) {
  return window['go']['bridge']['Bridge']['StartClock'](arg1);
}

export function StopClock() {
  return window['go']['bridge']['Bridge']['StopClock']();
}
