// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function SetContext(arg1:context.Context):Promise<void>;

export function StartClock(arg1:boolean):Promise<void>;

export function StopClock():Promise<void>;
