// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCustomDir() {
  return window['go']['bridge']['Bridge']['GetCustomDir']();
}

export function ListCustomSkin() {
  return window['go']['bridge']['Bridge']['ListCustomSkin']();
}

export function MediaNext() {
  return window['go']['bridge']['Bridge']['MediaNext']();
}

export function MediaPlayPause() {
  return window['go']['bridge']['Bridge']['MediaPlayPause']();
}

export function MediaPrevious() {
  return window['go']['bridge']['Bridge']['MediaPrevious']();
}

export function MediaStop() {
  return window['go']['bridge']['Bridge']['MediaStop']();
}

export function ReadCustomSkin(arg1) {
  return window['go']['bridge']['Bridge']['ReadCustomSkin'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bridge']['Bridge']['SetContext'](arg1);
}

export function StartAudio() {
  return window['go']['bridge']['Bridge']['StartAudio']();
}

export function StartClock(arg1) {
  return window['go']['bridge']['Bridge']['StartClock'](arg1);
}

export function StopAudio() {
  return window['go']['bridge']['Bridge']['StopAudio']();
}

export function StopClock() {
  return window['go']['bridge']['Bridge']['StopClock']();
}
