// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetSkinsDir():Promise<string>;

export function LaunchMusicPlayer():Promise<string>;

export function ListCustomSkins():Promise<string>;

export function LoadSettings():Promise<string>;

export function MediaNext():Promise<void>;

export function MediaPlayPause():Promise<void>;

export function MediaPrevious():Promise<void>;

export function MediaStop():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickBackground():Promise<string>;

export function PickMusicPlayer():Promise<string>;

export function PreventSleep():Promise<void>;

export function ReadCustomSkin(arg1:string):Promise<string>;

export function RestoreSleep():Promise<void>;

export function SaveSettings(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartAudio():Promise<string>;

export function StartClock(arg1:boolean):Promise<void>;

export function StartShortcutListener(arg1:context.Context):Promise<void>;

export function StopAudio():Promise<void>;

export function StopClock():Promise<void>;

export function UpdateShortcut(arg1:string):Promise<string>;
