// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetCustomDir():Promise<string>;

export function ListCustomSkin():Promise<string>;

export function MediaNext():Promise<void>;

export function MediaPlayPause():Promise<void>;

export function MediaPrevious():Promise<void>;

export function MediaStop():Promise<void>;

export function ReadCustomSkin(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartAudio():Promise<string>;

export function StartClock(arg1:boolean):Promise<void>;

export function StopAudio():Promise<void>;

export function StopClock():Promise<void>;
