// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSkinsDir() {
  return window['go']['bridge']['Bridge']['GetSkinsDir']();
}

export function ListCustomSkins() {
  return window['go']['bridge']['Bridge']['ListCustomSkins']();
}

export function LoadSettings() {
  return window['go']['bridge']['Bridge']['LoadSettings']();
}

export function MediaNext() {
  return window['go']['bridge']['Bridge']['MediaNext']();
}

export function MediaPlayPause() {
  return window['go']['bridge']['Bridge']['MediaPlayPause']();
}

export function MediaPrevious() {
  return window['go']['bridge']['Bridge']['MediaPrevious']();
}

export function MediaStop() {
  return window['go']['bridge']['Bridge']['MediaStop']();
}

export function OpenFolder(arg1) {
  return window['go']['bridge']['Bridge']['OpenFolder'](arg1);
}

export function PickBackground() {
  return window['go']['bridge']['Bridge']['PickBackground']();
}

export function PreventSleep() {
  return window['go']['bridge']['Bridge']['PreventSleep']();
}

export function ReadCustomSkin(arg1) {
  return window['go']['bridge']['Bridge']['ReadCustomSkin'](arg1);
}

export function RestoreSleep() {
  return window['go']['bridge']['Bridge']['RestoreSleep']();
}

export function SaveSettings(arg1) {
  return window['go']['bridge']['Bridge']['SaveSettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bridge']['Bridge']['SetContext'](arg1);
}

export function StartAudio() {
  return window['go']['bridge']['Bridge']['StartAudio']();
}

export function StartClock(arg1) {
  return window['go']['bridge']['Bridge']['StartClock'](arg1);
}

export function StopAudio() {
  return window['go']['bridge']['Bridge']['StopAudio']();
}

export function StopClock() {
  return window['go']['bridge']['Bridge']['StopClock']();
}
